spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/onlineshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.gjy.pojo
  mapper-locations: classpath:com/gjy/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true